# Generated by Django 5.1.7 on 2025-03-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_chatmessage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('name', 'event_type'), name='unique_event_name_type'),
        ),
    ]
