
# Generated by Django 5.1.7 on 2025-03-30 05:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventcategory_remove_event_unique_event_name_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
