# Generated by Django 5.1.7 on 2025-03-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updated_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='updated_date',
        ),
    ]
