# Generated by Django 5.1.7 on 2025-04-04 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='checkin_time',
            field=models.DateTimeField(null=True),
        ),
    ]
