# Generated by Django 5.1.7 on 2025-04-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_orderdetail_checked_in_orderdetail_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/%Y/%m/%d/'),
        ),
    ]
