# Generated by Django 5.1.7 on 2025-04-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_orderdetail_qr_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
