# Generated by Django 5.1.7 on 2025-04-08 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_google_maps_link'),
        ('events', '0008_alter_event_image_alter_user_avatar'),
    ]

    operations = [
    ]
