# Generated by Django 5.1.7 on 2025-04-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_merge_20250408_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='target_rank',
            field=models.CharField(blank=True, choices=[('bronze', 'Đồng'), ('silver', 'Bạc'), ('gold', 'Vàng'), ('none', 'Không có hạng')], default='none', help_text='Hạng khách hàng áp dụng (nếu để trống, áp dụng cho tất cả).', max_length=20, null=True),
        ),
    ]
