# Generated by Django 5.1.7 on 2025-04-23 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_orderdetail_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_limit',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
