# Generated by Django 5.1.7 on 2025-05-16 04:28

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_orderdetail_google_calendar_event_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='orderdetail',
            name='qr_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
