"""
Django settings for eventgoapp project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

import oauth2_provider.contrib.rest_framework
import cloudinary
import cloudinary.uploader
import cloudinary.api
from oauth2_provider.contrib import rest_framework

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3*0)+zju75-6mb82)sr3ne#8qtv0*pl7w^s93hoc*3s0w87$a3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events.apps.EventsConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'oauth2_provider',
    'corsheaders',
    'django.contrib.sites',  # Bắt buộc cho allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'cloudinary',
    'cloudinary_storage',
]


cloudinary.config(
    cloud_name='dqpkxxzaf',
    api_key='948716666497639',
    api_secret='VxK3FJQ_0HFa4UeMXYI0nfSIGko'
)


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'events', 'static'),  # Chỉ định đúng đường dẫn
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Cấu hình URL chuyển hướng sau khi đăng nhập thành công
LOGIN_REDIRECT_URL = '/'

# Cấu hình URL chuyển hướng sau khi đăng xuất
LOGOUT_REDIRECT_URL = '/'

#30/3
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

#Tạm thời tắt đi
# OAUTH2_PROVIDER = {
#     'ACCESS_TOKEN_EXPIRE_SECONDS': 3600,  # Token hết hạn sau 1 giờ
# }

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '782723098529-vrc06mm3l9oj92crt6bcpnnpsgupjh28.apps.googleusercontent.com',
            'secret': '<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>',
            'key': '',
        }
    }
}

ACCOUNT_LOGIN_METHODS = {'email', 'username'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "optional"



#29/3
# không thể dùng email vì không có money mua gg cloud tạo API
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'trvannhanh@gmail.com'
# EMAIL_HOST_PASSWORD = '@Giidavibe2004'

#Lỗi r đau đầu quá đ chạy đc
# # Dùng Mailgun thay vì
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.mailgun.org'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'postmaster@sandbox9870d6bed4c74fe084eb0ba5d3ed2721.mailgun.org'  # Thay bằng tài khoản Mailgun của bạn
# EMAIL_HOST_PASSWORD = '@Giidavibe2004'  # Thay bằng mật khẩu Mailgun
# DEFAULT_FROM_EMAIL = 'trvannhanh@gmail.com'  # Địa chỉ email gửi

#29/3
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['oauth2_provider.contrib.rest_framework.OAuth2Authentication']
}

CKEDITOR_UPLOAD_PATH = 'ckeditor/images/'


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #đặt ở đầu để kiểm tra domain trước
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

CORS_ALLOWED_ALL_ORIGINS = True #CORS cho phép hết (ALL)

AUTH_USER_MODEL = 'events.User'

ROOT_URLCONF = 'eventgoapp.urls'

MEDIA_ROOT = f'{BASE_DIR}/events/static/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eventgoapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eventdb',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#29/3
CLIENT_ID = 'LugOVBYQ40AG5gX2rZLrJ06QwMfURLu53KMZ5uUR'
CLIENT_SECRET = 'UhLGgZO3EUw2TjWsTH9pj0ZIghx4geIwIcQX3dBe7BJaCwMkVgZJEKKEKcbhWyDOcm1fDnGowDdAo086zXO1wtEIVAuwmbtiH6sWwRBVPYxJ0c3U8wuYtriI8ZjoklAM'

GOOGLE_CLIENT_ID = '782723098529-vrc06mm3l9oj92crt6bcpnnpsgupjh28.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '<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>'


# https://accounts.google.com/o/oauth2/auth?
# client_id=782723098529-vrc06mm3l9oj92crt6bcpnnpsgupjh28.apps.googleusercontent.com&
# redirect_uri=http://localhost:8000/auth/complete/google/&
# response_type=code&
# scope=email%20profile&
# access_type=offline
