"""
Django settings for eventgoapp project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

import oauth2_provider.contrib.rest_framework
import cloudinary
import cloudinary.uploader
import cloudinary.api
from oauth2_provider.contrib import rest_framework

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3*0)+zju75-6mb82)sr3ne#8qtv0*pl7w^s93hoc*3s0w87$a3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.0.2.2', 'localhost', '127.0.0.1', "192.168.1.41", "10.17.50.147", "192.168.79.103"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events.apps.EventsConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'oauth2_provider',
    'corsheaders',
    'django.contrib.sites',  # Bắt buộc cho allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'django_celery_beat',
    'push_notifications', # 4/5
    'cloudinary',
    'cloudinary_storage',
    'drf_yasg',
    'debug_toolbar',
    'channels',  # For real-time chat
]





cloudinary.config(
    cloud_name='dqpkxxzaf',
    api_key='948716666497639',
    api_secret='VxK3FJQ_0HFa4UeMXYI0nfSIGko'
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'events', 'static'),  # Chỉ định đúng đường dẫn
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Cấu hình URL chuyển hướng sau khi đăng nhập thành công
LOGIN_REDIRECT_URL = '/'

# Cấu hình URL chuyển hướng sau khi đăng xuất
LOGOUT_REDIRECT_URL = '/'

#30/3
SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

GOOGLE_CALENDAR_API = {
    'CLIENT_ID': '782723098529-vrc06mm3l9oj92crt6bcpnnpsgupjh28.apps.googleusercontent.com',
    'CLIENT_SECRET': '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',
    'REDIRECT_URI': 'http://localhost:8000/auth/google/callback/',
    'SCOPES': ['https://www.googleapis.com/auth/calendar.events'],
}


ACCOUNT_AUTHENTICATION_METHOD = 'username_email'  # Cho phép đăng nhập bằng username hoặc email
ACCOUNT_EMAIL_VERIFICATION = "optional"





EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  
EMAIL_PORT = 587  # Typically 587 for TLS
EMAIL_USE_TLS = True  # Use TLS for secure connection
EMAIL_HOST_USER = 'nhanhgon24@gmail.com'  
EMAIL_HOST_PASSWORD = 'ozxs stip hhfs amtr'  
DEFAULT_FROM_EMAIL = 'nhanhgon24@gmail.com'

#29/3
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': ['oauth2_provider.contrib.rest_framework.OAuth2Authentication']
}

CKEDITOR_UPLOAD_PATH = 'ckeditor/images/'


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', #đặt ở đầu để kiểm tra domain trước
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

CORS_ALLOWED_ALL_ORIGINS = True #CORS cho phép hết (ALL)

AUTH_USER_MODEL = 'events.User'

ROOT_URLCONF = 'eventgoapp.urls'

MEDIA_ROOT = f'{BASE_DIR}/events/static/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'eventgoapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'eventdb',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    '127.0.0.1'
]

#29/3

CLIENT_ID = 'RMc1aqYSM98ld8ulAOy1FAyvubnPJiWCeWnnefPC'
CLIENT_SECRET = 'pVmRNtsbnYZj7j0vYEbg20GoV8JE74HA4ZG74Ggqxw0OD0a3Qqlz2LGM2M6DVkArIolR3pTv4Kh7Z4mmu5CDqAhUIsOoyDCX8eKoQeRSGWVmwfFVljwtBbicN2EOrozT'


GOOGLE_CLIENT_ID = '782723098529-vrc06mm3l9oj92crt6bcpnnpsgupjh28.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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'

FACEBOOK_ID = '1390840525421151'
FACKEBOOK_SECRET = '4677af425a1550366a18fe756cf0c0a9'


CELERY_BROKER_URL = 'redis://:Admin123@192.168.79.103:6379/0'
CELERY_RESULT_BACKEND = 'redis://:Admin123@192.168.79.103:6379/0'

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:Admin123@192.168.79.103:6379/1",  # database số 1
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "PASSWORD": "Admin123",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
